version: '3'

services:
  etcd:
    image: soyking/etcd-goreman:3.2.7
    ports:
      - "6179:2379"
      - "6180:2379"
      - "6181:2379"
    environment:
      - CLIENT_ADDR=etcd
  e3w:
    image: soyking/e3w:latest
    volumes:
      - ./conf/config.default.ini:/app/conf/config.default.ini
    ports:
      - "6192:8080"
    depends_on:
      - etcd
